### ISSUE TITLE
Aliens: Dark Descent save file incompatibility

### ISSUE THREAD

**Issue by korgano** [trumank/uesave-rs#10]
Tried using the latest version to edit a save* from Aliens: Dark Descent, and got the following error:
```
Found non-standard magic: [ed, c0, da, 71] (   q) expected: GVAS, continuing to parse...
Error: io error: failed to fill whole buffer

Caused by:
    failed to fill whole buffer
```

No idea what's going on here, but I'm providing the .sav file to help you figure it out.

[CampaignData.zip](https://github.com/trumank/uesave-rs/files/13198054/CampaignData.zip)

*The game as **multiple** .sav files, some dedicated to specific maps, so that could possibly be part of the problem.

**Comment by trumank** [comment]
This save has some kind of compression or encryption applied which would be a game specific modification. I would expect to see some plain text strings in the save if it were a standard UE save file. At a glance I don't recognize any compression headers like LZMA or Oodle, which seem to be the more common types of post processing applied.

<img width="760" alt="Screen Shot 2023-10-29 at 11 55 05 AM" src="https://github.com/trumank/uesave-rs/assets/1144160/227db3ac-5bfd-4bde-a542-6b4df93003ec">
