### ISSUE TITLE
Unable to edit Help Wanted 2 savegame

### ISSUE THREAD

**Issue by xAstroBoy** [trumank/uesave-rs#12]
C:\Users\xAstroBoy\AppData\Local\HW2\Saved\SaveGames>uesave edit Slot0.sav
StructType for ".SavedTags" unspecified, assuming Guid
Error: io error: failed to fill whole buffer

Caused by:
    failed to fill whole buffer

C:\Users\xAstroBoy\AppData\Local\HW2\Saved\SaveGames>

https://drive.google.com/file/d/1aJ0B0aZu3UHmSWrN49Vohjivn_4nnDrJ/view?usp=sharing

**Comment by trumank** [comment]
Just needs a couple of ambiguous types to be manually specified:
`uesave edit -t .SavedTags=Struct -t .TaggedCounters.Key=Struct Slot0.sav`
