### ISSUE TITLE
Unable to edit Asgard Wrath 2 save file

### ISSUE THREAD

**Issue by xAstroBoy** [trumank/uesave-rs#14]
https://drive.google.com/file/d/1wH9IEM1A1b1lbKgauVWnY4eUiT8Kdanx/view?usp=sharing

C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>uedit
'uedit' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>uesave edit __aw_global_data.sav
StructType for ".SettingsData.SettingsSubmenuToButtonData.Value" unspecified, assuming Struct(None)
StructType for ".SettingsData.SettingsSubmenuToButtonData.buttonData.Value" unspecified, assuming Struct(None)
Error: unknown property type: "m_eButtonType"

C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>uesave edit __temp_slot.sav
Error: unknown property type: "UInt64Property"

C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>

**Comment by trumank** [comment]
```
# type is not actually a vector, looks like it's just 3 ints, but a vector is the same size and allows it to parse
uesave test-resave test-data/issue14/__temp_slot.sav -t .StatsSaveData.m_values.Value=Vector
Error: Resave did not match

uesave test-resave test-data/issue14/__aw_global_data.sav
Resave successful
```
Mostly fixed in d8c1e7c but `__temp_slot.sav` is now running into the same duplicate entry issue as #13 and will silently drop a few members upon resave:
![image](https://github.com/trumank/uesave-rs/assets/1144160/c2feb3df-df5c-4031-b511-56f9b8c77cee)

**Comment by xAstroBoy** [comment]
oh, hopefully it can be fixed and solved

**Comment by NM69421** [comment]
> https://drive.google.com/file/d/1wH9IEM1A1b1lbKgauVWnY4eUiT8Kdanx/view?usp=sharing
> 
> C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>uedit 'uedit' is not recognized as an internal or external command, operable program or batch file.
> 
> C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>uesave edit __aw_global_data.sav StructType for ".SettingsData.SettingsSubmenuToButtonData.Value" unspecified, assuming Struct(None) StructType for ".SettingsData.SettingsSubmenuToButtonData.buttonData.Value" unspecified, assuming Struct(None) Error: unknown property type: "m_eButtonType"
> 
> C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>uesave edit __temp_slot.sav Error: unknown property type: "UInt64Property"
> 
> C:\Users\xAstroBoy\Desktop\editme\editme\apps\com.Sanzaru.Wrath2\f\UE4Game\Wrath2\Wrath2\Saved\SaveGames>

I know this will sound very stupid, but where did you find the save files on the quest, I only have a "Logs" folder inside of the "Saved" folder and thats empty.
