### ISSUE TITLE
Ghostbuster VR

### ISSUE THREAD

**Issue by xAstroBoy** [trumank/uesave-rs#17]
Unable to edit this file

C:\Users\xAstroBoy\Desktop\editme>uesave edit GB_LocalSettings.sav
StructType for ".EquipmentUpgradeLevels.Key" unspecified, assuming Guid
Error: io error: failed to fill whole buffer

Caused by:
    failed to fill whole buffer

C:\Users\xAstroBoy\Desktop\editme>

https://drive.google.com/file/d/1dVCqJnKC6L7VY0UkyCGytnAqsaeEB6vc/view?usp=sharing

**Comment by trumank** [comment]
needs `-t .EquipmentUpgradeLevels.Key=Struct`
