### ISSUE TITLE
assistance request - demonologist save file

### ISSUE THREAD

**Issue by 4cz36sae** [trumank/uesave-rs#18]
[PlayerAssetsRelease.zip](https://github.com/trumank/uesave-rs/files/13846011/PlayerAssetsRelease.zip)
 Hello Sir/Maam,
Thank you for creating this tool. When I try to use it on the attached save file I get the below error. From what I understand there needs to be some manual mapping done but the exact details are beyond me. Any suggestions for what is needed would be appreciated. Thank you.

Error message:
Error: io error: failed to fill whole buffer

Caused by:
    failed to fill whole buffer

**Comment by trumank** [comment]
Fixed by e0612264841330ee4533cae48584c177109215ec
