### ISSUE TITLE
Unable to edit save file, failed to fill whole buffer

### ISSUE THREAD

**Issue by cejecho** [trumank/uesave-rs#19]
Hello it seems failed when i trying to edit the ArtemisPlayerInfo, it says failed to fill whole buffer at offset 19720
Heres the link: [Save](https://drive.google.com/file/d/1Y2A6yvN4udq-D217CVE4VLZHPHA4OEMl/view?usp=sharing)
Thank you so much!
![image](https://github.com/trumank/uesave-rs/assets/121383271/f2e38202-e012-4dbd-87e0-3ec5ccbba586)

**Comment by trumank** [comment]
Requires manual type override: `-t .Data.PlayerCompletionState.Facts.Facts.Key=Struct`

**Comment by cejecho** [comment]
sorry, i have new problem
![cmd_CTSdgF23KO](https://github.com/trumank/uesave-rs/assets/121383271/70aa02d0-3c97-4e7b-839b-046f1c13729b)
i tried manual mapping but it still errors, and its beyond me
[ArtemisPlayerInfo.zip](https://github.com/trumank/uesave-rs/files/13929962/ArtemisPlayerInfo.zip)
