### ISSUE TITLE
i tried manual mapping and its still error

### ISSUE THREAD

**Issue by cejecho** [trumank/uesave-rs#20]
Requires manual type override: `-t .Data.PlayerCompletionState.Facts.Facts.Key=Struct`

_Originally posted by @trumank in https://github.com/trumank/uesave-rs/issues/19#issuecomment-1890591018_

Thank you so much for assisting me before, however i have new problem that when i tried manual mapping according to your answer
its still error. It was fine before im using manual mapping but this time its error
![cmd_CTSdgF23KO](https://github.com/trumank/uesave-rs/assets/121383271/5d54e218-496b-44e4-9268-a34ad4882c2d)
[ArtemisPlayerInfo.zip](https://github.com/trumank/uesave-rs/files/13929977/ArtemisPlayerInfo.zip)

**Comment by trumank** [comment]
Fixed with 68442f119afb169d9672d53ad42ec83402d00267 and required the following types:

`-t .Data.PlayerCompletionState.CompletedActivitiesAlways.Key=Struct -t .Data.PlayerCompletionState.Facts.Facts.Key=Struct -t .Data.PlayerCompletionState.SceneCompletion.Key=Struct`
