### ISSUE TITLE
Error: at offset 32109: unknown property type: ""

### ISSUE THREAD

**Issue by cejecho** [trumank/uesave-rs#21]
Hey its new file, turns out its error Error: at offset 32109: unknown property type: ""
Here's the save file. i don't know why its like that empty property type
![cmd_TcAxOcOVwX](https://github.com/trumank/uesave-rs/assets/121383271/088f0018-4731-4cf7-98ce-f9ad76655934)
[ArtemisVehicle.zip](https://github.com/trumank/uesave-rs/files/13930418/ArtemisVehicle.zip)

**Comment by trumank** [comment]
This one appears to have a custom struct (`LegoGraphPartInstance`) and probably others which would require some reverse engineering, and game specific serialization is outside the scope of this library.

The structure doesn't look to complex if someone wanted to work on it though:
![image](https://github.com/trumank/uesave-rs/assets/1144160/458bc048-f554-4d5f-b4da-4ea1519ba2dd)
