### ISSUE TITLE
Palworld save file incompatability

### ISSUE THREAD

**Issue by TristanWiley** [trumank/uesave-rs#22]
Hi! I saw some other GH issues here with various game incompatibilities/requests and figured I'd make one as well.

Looks like Palworld must have some compression that's causing it to not work with the tool. I get the following error:

```
Found non-standard magic: [62, 16, 00, 00] (b) expected: GVAS, continuing to parse...
Error: at offset 2674: io error: failed to fill whole buffer
```

Here's a couple sample player save files: 
[PalworldSaveFiles.zip](https://github.com/trumank/uesave-rs/files/13997616/PalworldSaveFiles.zip)

Any help would be appreciated!

**Comment by TristanWiley** [comment]
That makes sense! Might be a silly question, how did you go about decompressing the save files?

**Comment by TristanWiley** [comment]
That worked! Thanks so much! Let me know if you happen to figure out the inverse process. I really appreciate the help

**Comment by TristanWiley** [comment]
One more unrelated question, any idea what the file name structure is? I assume it relates to a Steam ID of some sort but I've spent hours trying to decipher it and how it's encoded and I can't figure it out. I know the 0000000000... file is for a user that creates the world. But the other ones are definitely related to some unique identifier for the user.

**Comment by mcd1992** [comment]
> One more unrelated question, any idea what the file name structure is? I assume it relates to a Steam ID of some sort but I've spent hours trying to decipher it and how it's encoded and I can't figure it out. I know the 0000000000... file is for a user that creates the world. But the other ones are definitely related to some unique identifier for the user.

Not sure either. I've been trying to figure it out so I can convert my dedicated server player.savs to another machine since those IDs are per-machine as well. So I can't just copy paste my Player/*.savs

The filename does match the first 32 bits of IndividualId and PlayerUId in the GVAS/json data.

**Comment by war3i4i** [comment]
> One more unrelated question, any idea what the file name structure is? I assume it relates to a Steam ID of some sort but I've spent hours trying to decipher it and how it's encoded and I can't figure it out. I know the 0000000000... file is for a user that creates the world. But the other ones are definitely related to some unique identifier for the user.

I've did some research and basically your Player.sav file has GUID's of your container (inventory) and other stuff. These GUID's then used inside Level.sav itself where it contains data about items / slots / item amounts inside these container GUID's

Example: 

![image](https://github.com/trumank/uesave-rs/assets/60820906/4a4b158e-3ae6-4995-8037-a192df2d62bb)

^My character CommonContainerId

After looking into Level.json you can search for this GUID and look at every item attached 

![image](https://github.com/trumank/uesave-rs/assets/60820906/9a6b8c39-b143-47e9-b028-f1cf54fcd348)

I think same logic applied to every other aspect of game and its containers and data holders. Basically your character is just a pointer-holder object that basically 100% depends on server

**Comment by trajedyraines** [comment]
Hello. 

I am trying to fix the BaseCampWorkerMax limit in Palworld, on my dedicated server. I have uesave but it does nothing. Is there a way to copy a file from a solo world that was generated with the limit increased? I understand the dedicated server files are a bit problematic but several sources online seem to think the process should work but I have not had that experience. 

Let me know if you know anything I can do to fix this.
Thanks.

**Comment by DKingAlpha** [comment]
This ByteProperty  seems to be breaking the deserialization. It could be possible the same problem of #24 

![image](https://github.com/trumank/uesave-rs/assets/15340687/67ee3346-4ce2-48ed-bb71-a8613d2c89b9)

![image](https://github.com/trumank/uesave-rs/assets/15340687/15f094a4-2f11-490a-ae2c-75addba97b95)

**Comment by DKingAlpha** [comment]
Yeah, this works now. https://github.com/DKingAlpha/palworld-uesave-rs

Converting back and forth, only floats differ. Bytes-accurate for other data.

**Comment by trumank** [comment]
Excellent work! Gonna close this now as it's out of scope for this repo.
