### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Remp2012** [trumank/uesave-rs#23]
Forgive me, I am completly green with installing packages in python. I only have one semester of it, and that was 5 years back. How do I install this so I can fix a save.
I tried "$ cargo install --git https://github.com/trumank/uesave-rs.git" and I get an invalid syntax. If I try "cargo install --git https://github.com/trumank/uesave-rs.git" i get an invalid syntax as well.

**Comment by trumank** [comment]
See the releases page for pre-built binaries: https://github.com/trumank/uesave-rs/releases
