### ISSUE TITLE
Unable to parse individual detached sav serialized data.

### ISSUE THREAD

**Issue by burpheart** [trumank/uesave-rs#24]
I noticed that part of the data in Palworld's game save is stored as ByteProperty type. The content here still seems to be serialized data of sav. However, when I tried to parse it using read_property, it returned an error and didn't work.

> called `Option::unwrap()` on a `None` value
thread 'tests::test_rw_property_int' panicked at 'called `Option::unwrap()` on a `None` value', src\lib.rs:822:36
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:117
   3: enum2$<core::option::Option<ref$<ref$<uesave::Header> > > >::unwrap<ref$<ref$<uesave::Header> > >
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\option.rs:935
   4: uesave::Vector::read<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:822
   5: enum2$<uesave::StructValue>::read<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:1434
   6: enum2$<uesave::Property>::read<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:2097
   7: uesave::read_property::closure$0<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:164
   8: uesave::Context<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >::scope<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > >,uesave::read_property::closure_env$0<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >,enum2$<core::result::Result<enum2$<
             at .\src\lib.rs:306
   9: uesave::read_property<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:161
  10: uesave::read_properties_until_none<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:140
  11: enum2$<uesave::StructValue>::read<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:1448
  12: enum2$<uesave::Property>::read<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:2097
  13: uesave::read_property::closure$0<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:164
  14: uesave::Context<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >::scope<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > >,uesave::read_property::closure_env$0<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >,enum2$<core::result::Result<enum2$<
             at .\src\lib.rs:306
  15: uesave::read_property<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >
             at .\src\lib.rs:161
  16: uesave::tests::rw_property::closure$0
             at .\src\lib.rs:2805
  17: uesave::Context<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > > >::run<std::io::cursor::Cursor<ref$<ref$<slice2$<u8> > > >,uesave::tests::rw_property::closure_env$0,enum2$<core::result::Result<tuple$<>,enum2$<uesave::error::Error> > > >
             at .\src\lib.rs:284
  18: uesave::tests::rw_property
             at .\src\lib.rs:2804
  19: uesave::tests::test_rw_property_int
             at .\src\lib.rs:2820
  20: uesave::tests::test_rw_property_int::closure$0
             at .\src\lib.rs:2817
  21: core::ops::function::FnOnce::call_once<uesave::tests::test_rw_property_int::closure_env$0,tuple$<> >
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\ops\function.rs:250
  22: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Here is an example of the data.
[data.dmp](https://github.com/trumank/uesave-rs/files/14014005/data.dmp)

**Comment by burpheart** [comment]
[data2.dmp](https://github.com/trumank/uesave-rs/files/14014055/data2.dmp)

**Comment by trumank** [comment]
Do you have an example of how you're calling it and the data in the byte array you're trying to parse?

**Comment by burpheart** [comment]
Although there are read and write functions, it seems that the library does not export functions for directly reading and writing properties.

**Comment by trumank** [comment]
Those functions are an implementation detail of the save format and aren't intended to be used externally. This version has modifications required to fully parse Palworld saves: https://github.com/DKingAlpha/palworld-uesave-rs
