### ISSUE TITLE
Fails to parse this file

### ISSUE THREAD

**Issue by bananaturtlesandwich** [trumank/uesave-rs#3]
[shattered.sav](https://github.com/trumank/uesave-rs/files/11594029/shattered.zip) fails with `Error: unknown vec type: BoolProperty`

**Comment by trumank** [comment]
Fixed in e184dc3 and 15fef64 though I'll have to revisit TextProperties at a later point. So far they haven't really shown up in saves (why would you want to serialize localized text?) so I haven't bothered.

**Comment by bananaturtlesandwich** [comment]
thank you!
