### ISSUE TITLE
guild fix selected with proper capitilization at the end of the line but still getting error below in terminal

### ISSUE THREAD

**Issue by JohnStark666** [trumank/uesave-rs#32]
python fix_host_save.py uesave.exe C:\Users\johnb\Desktop\New folder 1D983074000000000000000000000000 BA38DB13000000000000000000000000 True

invalid <guild_fix> argument. It should be either "True" or "False"

**Comment by trumank** [comment]
Issue with `fix_host_save.py`, not `uesave`
