### ISSUE TITLE
Error while modifying or converting (palworld) .sav files

### ISSUE THREAD

**Issue by ysn2382617094wsw** [trumank/uesave-rs#33]
How do I convert palworld's Level.sav to json and then json modification to .sav, I tried to use the help in -help but got some errors
[Level.zip](https://github.com/trumank/uesave-rs/files/14395279/Level.zip)
![QQ截图20240225130044](https://github.com/trumank/uesave-rs/assets/59820799/8a535b69-3612-4973-b44f-b1aa3a739dae)
Is there something wrong with my command or operation?

**Comment by trumank** [comment]
See #22
