### ISSUE TITLE
Frostpunk 2 parsing possible?

### ISSUE THREAD

**Issue by Willian-Zhang** [trumank/uesave-rs#39]
Thank you for making this amazing project!

I've been trying to decode FP2 save file  and make a tool that make meaningful changes to it. 
So far I have been successfully uncompress and recompress the game save from its raw save file [1.sav.zip](https://github.com/trumank/uesave-rs/files/15021279/1.sav.zip) with a custom tool that I built however can't seem to parse the seemingly GVAS content:
[1.sav.bin.zip](https://github.com/trumank/uesave-rs/files/15021273/1.sav.bin.zip)
There I found your tool amazing tool that could do GVAS parsing and maybe? unknown inline binary skipping. 
Are you interested at looking into this a bit? 

The file was saved with name `1` in case of you wonder what repeating of that text mean.

**Comment by trumank** [comment]
This obviously uses components of Unreal Engine serialization, but it structurally doesn't look at all similar to a typical UE save file. There is no GVAS magic, the header with UE version information is not present, and the properties don't really look right. To me it looks like a custom parser would be required.
