### ISSUE TITLE
Unable to load Medieval Dynasty save

### ISSUE THREAD

**Issue by Shoggomo** [trumank/uesave-rs#41]
I'm trying to edit a Medieval Dynasty save. There seem to be three missing types. I tried every type, that made sense to me, but could not get it to load. The missing types are `.LandscapeData.Value`, `.Buildings.ToolsBuffer_118_137A92324AB6747A399BA4B732BE0166.Value` and `.NPCs.PresetsIDs_166_980BA472412B10BA3984DCB92C30E02A.Value`.

I'm always getting this error: `Error: at offset 6133756: io error: failed to fill whole buffer`

Is there something I'm missing?
Here is my save file: 
[Autosave.zip](https://github.com/trumank/uesave-rs/files/15280814/Autosave.zip)

**Comment by trumank** [comment]
`ByteProperty` has two variants, one with just a single byte value and one with a string label in the case the `ByteProperty` is represending an enum with named keys. In the case of `ByteProperty` being used as keys in a `MapProperty`, it's currently assuming the string variant, but this save has both, and I don't see a way to disambiguously parse such structures. I may need to add a way to manually specify, like how types work currently. This is a patch that allows this particular save to parse:

```patch
diff --git a/src/lib.rs b/src/lib.rs
index c89ac32..12b13ed 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1605,7 +1605,17 @@ impl PropertyValue {
                 PropertyValue::SoftObject(read_string(reader)?, read_string(reader)?)
             }
             PropertyType::ObjectProperty => PropertyValue::Object(read_string(reader)?),
-            PropertyType::ByteProperty => PropertyValue::Byte(Byte::Label(read_string(reader)?)),
+            PropertyType::ByteProperty => PropertyValue::Byte({
+                let byte_keys = [
+                    ".NPCs.Dialogue_140_6358380044D8558348534F8C345DE45E.FirstConvers_42_848629774FB793214FB315B79A315190",
+                    ".UsedPresetsPerVillage",
+                ];
+                if byte_keys.contains(&reader.path().as_str()) {
+                    Byte::Byte(reader.read_u8()?)
+                } else {
+                    Byte::Label(read_string(reader)?)
+                }
+            }),
             PropertyType::EnumProperty => PropertyValue::Enum(read_string(reader)?),
             PropertyType::StructProperty => {
                 PropertyValue::Struct(StructValue::read(reader, st.as_ref().unwrap())?)
```

**Comment by Shoggomo** [comment]
Awesome, this seems to work. Thank you.
