### ISSUE TITLE
Abiotic Factor: unknown property type: "SkeletalData"

### ISSUE THREAD

**Issue by felis-lynx** [trumank/uesave-rs#43]
Hello There,
Great work really great tool.
Unfortunately i always get an Error when i try to use uesave with either "edit" or "to-json" subcommands on Abiotic Factor Save files.

`Error: at offset 4152: unknown property type: "SkeletalData_14_DD6AD2E6419D803E0B6737B90C6EED11"`

I've attached the Save file as a zip file.
[Player_76561198041379924.zip](https://github.com/trumank/uesave-rs/files/15473060/Player_76561198041379924.zip)

**Comment by trumank** [comment]
Fixed by #34
