### ISSUE TITLE
Can't edit lego 2K Drive save file

### ISSUE THREAD

**Issue by Losif-kun** [trumank/uesave-rs#44]
offset 7514: StructType for ".Data.PlayerCompletionState.TimedTasks.Value" unspecified, assuming Struct(None)
offset 9406: StructType for ".Data.PlayerCompletionState.CompletedActivitiesAlways.Key" unspecified, assuming Guid
offset 9406: StructType for ".Data.PlayerCompletionState.CompletedActivitiesAlways.Value" unspecified, assuming Struct(None)
Error: at offset 17400: io error: failed to fill whole buffer

I have tried using command
` -t .Data.PlayerCompletionState.CompletedActivitiesAlways.Key=Struct -t .Data.PlayerCompletionState.Facts.Facts.Key=Struct -t .Data.PlayerCompletionState.SceneCompletion.Key=Struct` but it doesn't work as well.

**Comment by trumank** [comment]
Please upload the save file

**Comment by Losif-kun** [comment]
[ArtemisPlayerInfo.zip](https://github.com/user-attachments/files/15664669/ArtemisPlayerInfo.zip)
zipped it because github doesnt support sav file

**Comment by trumank** [comment]
Tested with the same type flags as #20 and it works for me. If you aren't already, you may need to compile from source to get the necessary fixes as they have not made it to the release yet.

**Comment by Losif-kun** [comment]
how can I compile it from source on windows?
