### ISSUE TITLE
Suggestion: Find and edit any value

### ISSUE THREAD

**Issue by Vlxst** [trumank/uesave-rs#48]
Is it possible to add control to json using the command line entirely?

For example, find keys and edit values ​​based on our search?

It searches for the key Settings_Resolution_0
"Settings_Resolution_0": {
"Str": {
"value": "1280x800"
}
and edits the value automatically by a value that we added in a list (MAYBE?) before.

Thanks in advance

**Comment by trumank** [comment]
This tool's purpose is to convert to and from JSON. There are already great tools for editing JSON such as jq or python.
