### ISSUE TITLE
Missing support for DoubleProperty

### ISSUE THREAD

**Issue by mlindgren** [trumank/uesave-rs#5]
I'm trying to tinker with save file from _Made in Abyss: Binary Star Falling Into Darkness._ The application fails to parse the save with the following error:

`Error: at offset 1688: unknown property type: "DoubleProperty"`

I can see from the code that this property type is unsupported. I'm new to Rust, but I might take a crack at implementing support for it myself, but can't promise anything. The failing save file is attached.
[Slot05.zip](https://github.com/trumank/uesave-rs/files/12141532/Slot05.zip)

**Comment by trumank** [comment]
I've added DoubleProperty but seems there's a bigger issue with parsing this particular save:

    56699 extra bytes. Save may not have been parsed completely.

I've only seen a few saves with such extra data. I suspect it's custom serialization for the particular game's save struct type and may not be possible to parse without extra context.

**Comment by mlindgren** [comment]
Wow, that was fast. I submitted my own PR but it looks like you beat me to it. Weren't expecting you to respond so quickly 😅

I found the same thing; you're probably right that there's a lot of custom serialization going on here.
