### ISSUE TITLE
Resident Evil VR (quest)

### ISSUE THREAD

**Issue by xAstroBoy** [trumank/uesave-rs#52]
https://drive.google.com/file/d/1aAlHQTvtrjrcGSClCE9bMJWd0SlaPrSO/view?usp=sharing

C:\Users\xAstroBoy\Desktop\Resident Evil 4 VR mod>uesave edit savegame00.sav
Found non-standard magic: [00, 00, 00, 00] (    ) expected: GVAS, continuing to parse...
Error: at offset 46: unknown property type: ""

i know there's a savegame editor for it, but i wonder if we can even make it better with json editing.
EDIT : i checked the source of it, and he made it way complicated when this could have been decrypted and then converted into json and easily edit it.

https://github.com/dubiousnerd/re4vr-save-editor/tree/dev

**Comment by trumank** [comment]
This save looks nothing like a UE save file. It's almost entirely null bytes and has nothing that looks like it's a string or anything that could be decrypted to a string.

**Comment by xAstroBoy** [comment]
> This save looks nothing like a UE save file. It's almost entirely null bytes and has nothing that looks like it's a string or anything that could be decrypted to a string.

launching the game there's the unreal engine logo on the bootup, maybe have a peek in the save editor and could possibly decrypt it?

**Comment by trumank** [comment]
I'm sure it's Unreal Engine, but I highly doubt they used the default save mechanism. Looks like they rolled their own.
