### ISSUE TITLE
Remnant 2

### ISSUE THREAD

**Issue by thewhitegoatcb** [trumank/uesave-rs#8]
Hello, 
this is probably unrelated as it doesn't seem to have much similar to GSAV format but it uses some serialization, since I don't have much experience in UE, some of you might recognize it.

[profile_save.zip](https://github.com/trumank/uesave-rs/files/12509621/profile_save.zip)

the save composed of zlib chunks, I have used this to extract it https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/main/RemnantSaveGuardian/RemnantSave.cs#L198
the output is `profile.sav.dec`.
which seems to be `Engine/Source/Runtime/Core/Private/Serialization/Archive.cpp`,  with an additional header

my suspicion is `Engine/Source/Runtime/CoreUObject/Private/Serialization/BulkData.cpp` is involved for the searlization, is there other projects that deserialize this or does it have anything in common with GSAV to adapt it ?

**Comment by trumank** [comment]
It definitely shares similarities with normal save files given it's still based on Unreal Engine serialization, but the structure is not the same at all. Here's a tool that should be able to parse it: https://github.com/Brabb3l/Remnant-2-Save-Parser
